services:
  vk2tg:
    build: .
    image: ghcr.io/kolx0zhik/vk_to_tg_poster:latest
    container_name: vk_to_tg_poster
    restart: unless-stopped
    ports:
      - "8222:8222"
    environment:
      - TZ=${TZ:-Europe/Moscow}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
